/**
 * stainedglass.js
 * Irregular Voronoi-cell "stained glass" / mosaic stepping-stone pieces from
 * a blue-noise (Poisson-disc) scatter of seed points, with a lead-line/grout
 * border drawn between adjacent pieces. Ported from mosaic_core.py's
 * make_mulberry32 / poisson_disc_points / sample_stainedglass_colors /
 * render_stainedglass_mosaic (same formulas, same op-for-op arithmetic for
 * the PRNG and Poisson-disc so seed layouts land on the exact same points
 * as the Python side for the same inputs -- see mosaic_core.py's stained
 * glass section header for why that specific piece needs to be trig-free
 * and bit-identical while the nearest-seed lookup used for sampling/
 * rendering does not).
 */

// Same headroom as RADIAL_MAX_CELLS, for the same reasons.
export const STAINEDGLASS_MAX_CELLS = 20000;
// Empirical: canvas_area / (min_dist^2 * count) averages ~1.6 for Bridson
// Poisson-disc output -- see mosaic_core.py's STAINEDGLASS_PACKING_FACTOR.
export const STAINEDGLASS_PACKING_FACTOR = 1.6;

/** Deterministic [0, 1) float generator from an integer seed. All
 * arithmetic stays in unsigned-32-bit-modular form (>>> 0 after every
 * add/multiply), matching mosaic_core.py's make_mulberry32 line for line --
 * see that function's docstring for why this is safe to treat as
 * equivalent to Python's masked-integer arithmetic. */
export function makeMulberry32(seed) {
  let state = seed >>> 0;
  return function next() {
    state = (state + 0x6D2B79F5) >>> 0;
    let t = state;
    t = (Math.imul(t ^ (t >>> 15), t | 1)) >>> 0;
    const t2 = (Math.imul(t ^ (t >>> 7), t | 61)) >>> 0;
    t = (t ^ ((t + t2) >>> 0)) >>> 0;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Bridson's Poisson-disc sampling -- a blue-noise scatter of points over a
 * width x height rectangle, no two closer than minDist. Candidate points
 * are generated by rejection-sampling an offset in the annulus [minDist,
 * 2*minDist] around an active point, deliberately never using sin/cos (see
 * module docstring). Returns an array of [x, y] pairs; deterministic for a
 * given seed, and verified bit-identical to the Python port for every seed
 * tried during development. */
export function poissonDiscPoints(width, height, minDist, seed, k = 30, maxInnerTries = 200) {
  const rng = makeMulberry32(seed);
  const cellSize = minDist / Math.sqrt(2);
  const gridW = Math.max(1, Math.ceil(width / cellSize));
  const gridH = Math.max(1, Math.ceil(height / cellSize));
  const grid = new Array(gridW * gridH).fill(-1);
  const points = [];
  const active = [];

  function gridIndex(x, y) {
    const gx = Math.min(gridW - 1, Math.max(0, Math.floor(x / cellSize)));
    const gy = Math.min(gridH - 1, Math.max(0, Math.floor(y / cellSize)));
    return [gx, gy];
  }

  function farEnough(x, y) {
    if (x < 0 || x >= width || y < 0 || y >= height) return false;
    const [gx, gy] = gridIndex(x, y);
    const x0 = Math.max(0, gx - 2), x1 = Math.min(gridW - 1, gx + 2);
    const y0 = Math.max(0, gy - 2), y1 = Math.min(gridH - 1, gy + 2);
    for (let iy = y0; iy <= y1; iy++) {
      for (let ix = x0; ix <= x1; ix++) {
        const idx = grid[iy * gridW + ix];
        if (idx === -1) continue;
        const [px, py] = points[idx];
        const dx = px - x, dy = py - y;
        if (dx * dx + dy * dy < minDist * minDist) return false;
      }
    }
    return true;
  }

  function addPoint(x, y) {
    const idx = points.length;
    points.push([x, y]);
    active.push(idx);
    const [gx, gy] = gridIndex(x, y);
    grid[gy * gridW + gx] = idx;
  }

  addPoint(rng() * width, rng() * height);

  while (active.length > 0) {
    let activeI = Math.floor(rng() * active.length);
    if (activeI >= active.length) activeI = active.length - 1;
    const [px, py] = points[active[activeI]];
    let found = false;
    for (let attempt = 0; attempt < k; attempt++) {
      let dx = 0, dy = 0;
      for (let inner = 0; inner < maxInnerTries; inner++) {
        dx = rng() * 4 * minDist - 2 * minDist;
        dy = rng() * 4 * minDist - 2 * minDist;
        const d2 = dx * dx + dy * dy;
        if (d2 >= minDist * minDist && d2 <= (2 * minDist) * (2 * minDist)) break;
      }
      const cx = px + dx, cy = py + dy;
      if (farEnough(cx, cy)) {
        addPoint(cx, cy);
        found = true;
        break;
      }
    }
    if (!found) {
      active.splice(activeI, 1);
    }
  }

  return points;
}

/** Rough pre-generate estimate of how many pieces a given canvas size and
 * spacing will produce -- see mosaic_core.py's
 * estimate_stainedglass_piece_count for why this is only a "~" estimate. */
export function estimateStainedglassPieceCount(canvasW, canvasH, minDist) {
  if (minDist <= 0) return 0;
  return Math.max(1, Math.round((canvasW * canvasH) / (minDist * minDist * STAINEDGLASS_PACKING_FACTOR)));
}

/** [canvasW, canvasH] sized to roughly reach targetCount pieces at the
 * given piece spacing, preserving the source image's aspect ratio. Inverse
 * of estimateStainedglassPieceCount's packing formula. */
export function stainedglassCanvasSize(imageW, imageH, targetCount, minDist) {
  const aspect = imageH ? imageW / imageH : 1.0;
  const totalArea = targetCount * minDist * minDist * STAINEDGLASS_PACKING_FACTOR;
  const canvasH = Math.max(40, Math.round(Math.sqrt(totalArea / aspect)));
  const canvasW = Math.max(40, Math.round(aspect * canvasH));
  return [canvasW, canvasH];
}

/** Grid-accelerated nearest-neighbor index over a fixed point set, used
 * identically for sampling (source image pixels -> nearest seed) and
 * rendering (output canvas pixels -> nearest seed). This doesn't need to
 * match the Python side's search structure (scipy's cKDTree there) --
 * only the *nearest-by-Euclidean-distance* result does, which is a stable,
 * effectively tie-free comparison for a continuous random point set (unlike
 * seed generation above, which does need bit-identical arithmetic). */
function buildSeedIndex(points, width, height, minDist) {
  const cellSize = Math.max(1e-6, minDist / Math.sqrt(2));
  const gridW = Math.max(1, Math.ceil(width / cellSize));
  const gridH = Math.max(1, Math.ceil(height / cellSize));
  const buckets = new Array(gridW * gridH);
  for (let i = 0; i < buckets.length; i++) buckets[i] = [];
  for (let idx = 0; idx < points.length; idx++) {
    const [x, y] = points[idx];
    const gx = Math.min(gridW - 1, Math.max(0, Math.floor(x / cellSize)));
    const gy = Math.min(gridH - 1, Math.max(0, Math.floor(y / cellSize)));
    buckets[gy * gridW + gx].push(idx);
  }
  return { cellSize, gridW, gridH, buckets };
}

function nearestSeed(index, points, x, y) {
  const { cellSize, gridW, gridH, buckets } = index;
  const gx = Math.min(gridW - 1, Math.max(0, Math.floor(x / cellSize)));
  const gy = Math.min(gridH - 1, Math.max(0, Math.floor(y / cellSize)));
  let bestIdx = -1, bestD2 = Infinity;
  const maxRing = Math.max(gridW, gridH);
  for (let ring = 0; ring <= maxRing; ring++) {
    const x0 = Math.max(0, gx - ring), x1 = Math.min(gridW - 1, gx + ring);
    const y0 = Math.max(0, gy - ring), y1 = Math.min(gridH - 1, gy + ring);
    for (let iy = y0; iy <= y1; iy++) {
      for (let ix = x0; ix <= x1; ix++) {
        if (ring > 0 && ix > x0 && ix < x1 && iy > y0 && iy < y1) continue; // interior already scanned
        const bucket = buckets[iy * gridW + ix];
        for (let k = 0; k < bucket.length; k++) {
          const idx = bucket[k];
          const [px, py] = points[idx];
          const dx = px - x, dy = py - y;
          const d2 = dx * dx + dy * dy;
          if (d2 < bestD2) { bestD2 = d2; bestIdx = idx; }
        }
      }
    }
    if (bestIdx !== -1 && (ring * cellSize) * (ring * cellSize) >= bestD2) break;
    if (x0 === 0 && y0 === 0 && x1 === gridW - 1 && y1 === gridH - 1) break; // whole grid covered
  }
  return bestIdx;
}

/**
 * Average the source image's pixels into each seed's cell -- every source
 * pixel is mapped into the same canvasW x canvasH coordinate space the seed
 * points live in (a plain linear scale, same spirit as every other mode's
 * image-to-grid mapping) and assigned to its nearest seed. Zero-pixel cells
 * (possible for a very sparse layout over a tiny image) fall back to the
 * image's overall average color. Returns a flat array of [r, g, b] floats,
 * same order as `points`.
 */
export function sampleStainedglassColors(sourceCanvas, points, canvasW, canvasH, minDist) {
  if (!points.length) {
    throw new Error("No seed points to sample colors for.");
  }
  const ctx = sourceCanvas.getContext("2d");
  const sw = sourceCanvas.width, sh = sourceCanvas.height;
  if (sw <= 0 || sh <= 0) {
    throw new Error("Image has no pixels to sample.");
  }
  const src = ctx.getImageData(0, 0, sw, sh).data;

  const index = buildSeedIndex(points, canvasW, canvasH, minDist);
  const n = points.length;
  const sums = new Float64Array(n * 3);
  const counts = new Float64Array(n);
  let sumR = 0, sumG = 0, sumB = 0;

  for (let y = 0; y < sh; y++) {
    const cy = ((y + 0.5) / sh) * canvasH;
    for (let x = 0; x < sw; x++) {
      const cx = ((x + 0.5) / sw) * canvasW;
      const idx = nearestSeed(index, points, cx, cy);
      const srcIdx = (y * sw + x) * 4;
      const rr = src[srcIdx], gg = src[srcIdx + 1], bb = src[srcIdx + 2];
      sums[idx * 3] += rr; sums[idx * 3 + 1] += gg; sums[idx * 3 + 2] += bb;
      counts[idx]++;
      sumR += rr; sumG += gg; sumB += bb;
    }
  }

  const totalPixels = sw * sh;
  const overallAvg = [sumR / totalPixels, sumG / totalPixels, sumB / totalPixels];
  const colors = new Array(n);
  for (let i = 0; i < n; i++) {
    colors[i] = counts[i] > 0
      ? [sums[i * 3] / counts[i], sums[i * 3 + 1] / counts[i], sums[i * 3 + 2] / counts[i]]
      : overallAvg;
  }
  return colors;
}

/** 4-connected (cross) binary dilation by `iterations` steps -- matches
 * scipy.ndimage.binary_dilation's default structuring element in
 * mosaic_core.py's render_stainedglass_mosaic, so a given lead width looks
 * the same shape in both renders (not required for parity -- rendering
 * differences are tolerated the same way radial's polygon draw is -- but
 * cheap to match and keeps the two outputs visually consistent). */
function dilateCross(mask, w, h, iterations) {
  let current = mask;
  for (let it = 0; it < iterations; it++) {
    const next = new Uint8Array(current.length);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = y * w + x;
        if (current[i]) { next[i] = 1; continue; }
        if ((x > 0 && current[i - 1]) || (x < w - 1 && current[i + 1]) ||
            (y > 0 && current[i - w]) || (y < h - 1 && current[i + w])) {
          next[i] = 1;
        }
      }
    }
    current = next;
  }
  return current;
}

/**
 * Rasterizes the Voronoi mosaic directly (no polygon math): every output
 * pixel is colored by its nearest seed's quantized color, then a
 * lead-line/grout border is drawn wherever neighboring pixels belong to
 * different cells, thickened to roughly leadWidth pixels wide. Ported from
 * mosaic_core.py's render_stainedglass_mosaic -- see that function's
 * docstring for why rasterizing (rather than building actual Voronoi
 * polygons) is the design here.
 */
export function renderStainedglassMosaic(colors, points, canvasW, canvasH, minDist,
                                          leadWidth, leadColor, createCanvasFn) {
  const canvas = createCanvasFn(canvasW, canvasH);
  const ctx = canvas.getContext("2d");
  const imgData = ctx.createImageData(canvasW, canvasH);
  const data = imgData.data;

  const index = buildSeedIndex(points, canvasW, canvasH, minDist);
  const owner = new Int32Array(canvasW * canvasH);
  for (let y = 0; y < canvasH; y++) {
    for (let x = 0; x < canvasW; x++) {
      owner[y * canvasW + x] = nearestSeed(index, points, x + 0.5, y + 0.5);
    }
  }

  let boundary = null;
  if (leadWidth > 0) {
    boundary = new Uint8Array(canvasW * canvasH);
    for (let y = 0; y < canvasH; y++) {
      for (let x = 0; x < canvasW; x++) {
        const i = y * canvasW + x;
        const o = owner[i];
        if (x < canvasW - 1 && owner[i + 1] !== o) { boundary[i] = 1; boundary[i + 1] = 1; }
        if (y < canvasH - 1 && owner[i + canvasW] !== o) { boundary[i] = 1; boundary[i + canvasW] = 1; }
      }
    }
    const extraIterations = Math.max(0, leadWidth - 1);
    if (extraIterations > 0) {
      boundary = dilateCross(boundary, canvasW, canvasH, extraIterations);
    }
  }

  for (let i = 0; i < canvasW * canvasH; i++) {
    let r, g, b;
    if (boundary && boundary[i]) {
      [r, g, b] = leadColor;
    } else {
      [r, g, b] = colors[owner[i]];
    }
    data[i * 4] = Math.round(r);
    data[i * 4 + 1] = Math.round(g);
    data[i * 4 + 2] = Math.round(b);
    data[i * 4 + 3] = 255;
  }
  ctx.putImageData(imgData, 0, 0);
  return canvas;
}
